POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "Clarc",
    "lastName": "Job",
    "email": "gfdh@gfcxg.com",
    "password": "ffsffhrtecxx#E34",
    "isSubscribed": true
}